### ISSUE TITLE
"That Wasn't Supposed to Happen..."

### ISSUE THREAD

**Issue by hparsons56** [Triumph-Tech/magnus-vscode#11]
First, thanks for this program, I KNOW it's going to help me tremendously, when I get it working, but I have a problem. I installed the plugin on my church's website, and the extension on my personal computer, and tried to log in. I didn't see a listing of files, and the VS console had an error message "Error: Unable to authorize with the server". I went back and checked my settings, and they all looked right, so I tried again. Same result. I checked the settings again, and this time, I got the ROCK error screen with "That wasn't supposed to happen". I figured I did something wrong, and completely reinstalled my RockRMS system (it was a new install, so not a big issue). I got everything set up, and basically went through the same process again.

This is the error code I get in the exception log:
NullReferenceException in tech.triumph.Magnus
Message
Object reference not set to an instance of an object.

Stack Trace

   at tech.triumph.Magnus.Utilities.MagnusHelpers.IpMatchesFilter(IPAddress ipAddress, IpAddressFilter ipAddressFilter) in C:\Development\Triumph-Rockit\tech.triumph.Magnus\Utilities\MagnusHelpers.cs:line 337
   at RockWeb.Plugins.tech_Triumph.Magnus.MagnusSettings.ShowView()
   at RockWeb.Plugins.tech_Triumph.Magnus.MagnusSettings.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean

**Comment by bradencohen** [comment]
@hparsons56 we found this exact could occur if there was an invalid IP address added to the filter. This has been fixed in v1.2, which is now available in the Rock Shop. If you're still encountering errors please feel free to re-open this issue!
